// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.23.3
// source: pbentity/user.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PLATFORM_TYPE int32

const (
	PLATFORM_TYPE_UNKNOWN_PLATFORM_TYPE PLATFORM_TYPE = 0
	PLATFORM_TYPE_IOS                   PLATFORM_TYPE = 1
	PLATFORM_TYPE_ANDROID               PLATFORM_TYPE = 2
	PLATFORM_TYPE_MAC                   PLATFORM_TYPE = 3
	PLATFORM_TYPE_WINDOWS               PLATFORM_TYPE = 4
	PLATFORM_TYPE_WEB                   PLATFORM_TYPE = 5
)

// Enum value maps for PLATFORM_TYPE.
var (
	PLATFORM_TYPE_name = map[int32]string{
		0: "UNKNOWN_PLATFORM_TYPE",
		1: "IOS",
		2: "ANDROID",
		3: "MAC",
		4: "WINDOWS",
		5: "WEB",
	}
	PLATFORM_TYPE_value = map[string]int32{
		"UNKNOWN_PLATFORM_TYPE": 0,
		"IOS":                   1,
		"ANDROID":               2,
		"MAC":                   3,
		"WINDOWS":               4,
		"WEB":                   5,
	}
)

func (x PLATFORM_TYPE) Enum() *PLATFORM_TYPE {
	p := new(PLATFORM_TYPE)
	*p = x
	return p
}

func (x PLATFORM_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PLATFORM_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pbentity_user_proto_enumTypes[0].Descriptor()
}

func (PLATFORM_TYPE) Type() protoreflect.EnumType {
	return &file_pbentity_user_proto_enumTypes[0]
}

func (x PLATFORM_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PLATFORM_TYPE.Descriptor instead.
func (PLATFORM_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pbentity_user_proto_rawDescGZIP(), []int{0}
}

type AVATAR_OWNER int32

const (
	AVATAR_OWNER_UNKNOWN_AVATAR_OWNER AVATAR_OWNER = 0
	AVATAR_OWNER_USER_AVATAR          AVATAR_OWNER = 1 // 用户头像
	AVATAR_OWNER_CHAT_AVATAR          AVATAR_OWNER = 2 // 群头像
)

// Enum value maps for AVATAR_OWNER.
var (
	AVATAR_OWNER_name = map[int32]string{
		0: "UNKNOWN_AVATAR_OWNER",
		1: "USER_AVATAR",
		2: "CHAT_AVATAR",
	}
	AVATAR_OWNER_value = map[string]int32{
		"UNKNOWN_AVATAR_OWNER": 0,
		"USER_AVATAR":          1,
		"CHAT_AVATAR":          2,
	}
)

func (x AVATAR_OWNER) Enum() *AVATAR_OWNER {
	p := new(AVATAR_OWNER)
	*p = x
	return p
}

func (x AVATAR_OWNER) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AVATAR_OWNER) Descriptor() protoreflect.EnumDescriptor {
	return file_pbentity_user_proto_enumTypes[1].Descriptor()
}

func (AVATAR_OWNER) Type() protoreflect.EnumType {
	return &file_pbentity_user_proto_enumTypes[1]
}

func (x AVATAR_OWNER) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AVATAR_OWNER.Descriptor instead.
func (AVATAR_OWNER) EnumDescriptor() ([]byte, []int) {
	return file_pbentity_user_proto_rawDescGZIP(), []int{1}
}

type ACCOUNT_TYPE int32

const (
	ACCOUNT_TYPE_UNKNOWN_ACCOUNT_TYPE ACCOUNT_TYPE = 0
	ACCOUNT_TYPE_MOBILE               ACCOUNT_TYPE = 1 // 手机登录
	ACCOUNT_TYPE_LARK                 ACCOUNT_TYPE = 2 // lark账户登录
)

// Enum value maps for ACCOUNT_TYPE.
var (
	ACCOUNT_TYPE_name = map[int32]string{
		0: "UNKNOWN_ACCOUNT_TYPE",
		1: "MOBILE",
		2: "LARK",
	}
	ACCOUNT_TYPE_value = map[string]int32{
		"UNKNOWN_ACCOUNT_TYPE": 0,
		"MOBILE":               1,
		"LARK":                 2,
	}
)

func (x ACCOUNT_TYPE) Enum() *ACCOUNT_TYPE {
	p := new(ACCOUNT_TYPE)
	*p = x
	return p
}

func (x ACCOUNT_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ACCOUNT_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_pbentity_user_proto_enumTypes[2].Descriptor()
}

func (ACCOUNT_TYPE) Type() protoreflect.EnumType {
	return &file_pbentity_user_proto_enumTypes[2]
}

func (x ACCOUNT_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ACCOUNT_TYPE.Descriptor instead.
func (ACCOUNT_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_pbentity_user_proto_rawDescGZIP(), []int{2}
}

type Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid       int64       `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty" dc:"uid" dc:"uid" dc:"uid" dc:"uid" dc:"uid"`                                          // uid
	LarkId    string      `protobuf:"bytes,2,opt,name=lark_id,json=larkId,proto3" json:"lark_id,omitempty" dc:"账户ID" dc:"账户ID" dc:"账户ID" dc:"账户ID" dc:"账户ID"`                  // 账户ID
	Status    int32       `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty" dc:"用户状态" dc:"用户状态" dc:"用户状态" dc:"用户状态" dc:"用户状态"`                               // 用户状态
	Nickname  string      `protobuf:"bytes,4,opt,name=nickname,proto3" json:"nickname,omitempty" dc:"昵称" dc:"昵称" dc:"昵称" dc:"昵称" dc:"昵称"`                                      // 昵称
	Firstname string      `protobuf:"bytes,5,opt,name=firstname,proto3" json:"firstname,omitempty" dc:"firstname" dc:"firstname" dc:"firstname" dc:"firstname" dc:"firstname"` // firstname
	Lastname  string      `protobuf:"bytes,6,opt,name=lastname,proto3" json:"lastname,omitempty" dc:"lastname" dc:"lastname" dc:"lastname" dc:"lastname" dc:"lastname"`        // lastname
	Gender    int32       `protobuf:"varint,7,opt,name=gender,proto3" json:"gender,omitempty" dc:"性别" dc:"性别" dc:"性别" dc:"性别" dc:"性别"`                                         // 性别
	BirthTs   int64       `protobuf:"varint,8,opt,name=birth_ts,json=birthTs,proto3" json:"birth_ts,omitempty" dc:"生日" dc:"生日" dc:"生日" dc:"生日" dc:"生日"`                        // 生日
	Mobile    string      `protobuf:"bytes,9,opt,name=mobile,proto3" json:"mobile,omitempty" dc:"手机号" dc:"手机号" dc:"手机号" dc:"手机号" dc:"手机号"`                                     // 手机号
	CityId    int64       `protobuf:"varint,10,opt,name=city_id,json=cityId,proto3" json:"city_id,omitempty" dc:"城市ID" dc:"城市ID" dc:"城市ID" dc:"城市ID" dc:"城市ID"`                // 城市ID
	Avatar    *AvatarInfo `protobuf:"bytes,11,opt,name=avatar,proto3" json:"avatar,omitempty" dc:"头像" dc:"头像" dc:"头像" dc:"头像" dc:"头像"`                                         // 头像
}

func (x *Info) Reset() {
	*x = Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbentity_user_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Info) ProtoMessage() {}

func (x *Info) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_user_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Info.ProtoReflect.Descriptor instead.
func (*Info) Descriptor() ([]byte, []int) {
	return file_pbentity_user_proto_rawDescGZIP(), []int{0}
}

func (x *Info) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *Info) GetLarkId() string {
	if x != nil {
		return x.LarkId
	}
	return ""
}

func (x *Info) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Info) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Info) GetFirstname() string {
	if x != nil {
		return x.Firstname
	}
	return ""
}

func (x *Info) GetLastname() string {
	if x != nil {
		return x.Lastname
	}
	return ""
}

func (x *Info) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *Info) GetBirthTs() int64 {
	if x != nil {
		return x.BirthTs
	}
	return 0
}

func (x *Info) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Info) GetCityId() int64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *Info) GetAvatar() *AvatarInfo {
	if x != nil {
		return x.Avatar
	}
	return nil
}

type AvatarInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OwnerId      int64        `protobuf:"varint,1,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty"`
	OwnerType    AVATAR_OWNER `protobuf:"varint,2,opt,name=owner_type,json=ownerType,proto3,enum=pbentity.AVATAR_OWNER" json:"owner_type,omitempty"`
	AvatarSmall  string       `protobuf:"bytes,3,opt,name=avatar_small,json=avatarSmall,proto3" json:"avatar_small,omitempty"`
	AvatarMedium string       `protobuf:"bytes,4,opt,name=avatar_medium,json=avatarMedium,proto3" json:"avatar_medium,omitempty"`
	AvatarLarge  string       `protobuf:"bytes,5,opt,name=avatar_large,json=avatarLarge,proto3" json:"avatar_large,omitempty"`
}

func (x *AvatarInfo) Reset() {
	*x = AvatarInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pbentity_user_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AvatarInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvatarInfo) ProtoMessage() {}

func (x *AvatarInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_user_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvatarInfo.ProtoReflect.Descriptor instead.
func (*AvatarInfo) Descriptor() ([]byte, []int) {
	return file_pbentity_user_proto_rawDescGZIP(), []int{1}
}

func (x *AvatarInfo) GetOwnerId() int64 {
	if x != nil {
		return x.OwnerId
	}
	return 0
}

func (x *AvatarInfo) GetOwnerType() AVATAR_OWNER {
	if x != nil {
		return x.OwnerType
	}
	return AVATAR_OWNER_UNKNOWN_AVATAR_OWNER
}

func (x *AvatarInfo) GetAvatarSmall() string {
	if x != nil {
		return x.AvatarSmall
	}
	return ""
}

func (x *AvatarInfo) GetAvatarMedium() string {
	if x != nil {
		return x.AvatarMedium
	}
	return ""
}

func (x *AvatarInfo) GetAvatarLarge() string {
	if x != nil {
		return x.AvatarLarge
	}
	return ""
}

var File_pbentity_user_proto protoreflect.FileDescriptor

var file_pbentity_user_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0xb1, 0x02, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6c, 0x61,
	0x72, 0x6b, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x72,
	0x6b, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x69, 0x63, 0x6b, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x5f, 0x74, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x62, 0x69, 0x72,
	0x74, 0x68, 0x54, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x63,
	0x69, 0x74, 0x79, 0x49, 0x64, 0x12, 0x2c, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18,
	0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x76, 0x61,
	0x74, 0x61, 0x72, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x41, 0x76, 0x61, 0x74, 0x61, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x35, 0x0a,
	0x0a, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x16, 0x2e, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x56, 0x41,
	0x54, 0x41, 0x52, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x52, 0x09, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x73,
	0x6d, 0x61, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x74,
	0x61, 0x72, 0x53, 0x6d, 0x61, 0x6c, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x76, 0x61, 0x74, 0x61,
	0x72, 0x5f, 0x6d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4d, 0x65, 0x64, 0x69, 0x75, 0x6d, 0x12, 0x21, 0x0a, 0x0c,
	0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x5f, 0x6c, 0x61, 0x72, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x4c, 0x61, 0x72, 0x67, 0x65, 0x2a,
	0x5f, 0x0a, 0x0d, 0x50, 0x4c, 0x41, 0x54, 0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45,
	0x12, 0x19, 0x0a, 0x15, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x50, 0x4c, 0x41, 0x54,
	0x46, 0x4f, 0x52, 0x4d, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x49,
	0x4f, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x41, 0x4e, 0x44, 0x52, 0x4f, 0x49, 0x44, 0x10,
	0x02, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x41, 0x43, 0x10, 0x03, 0x12, 0x0b, 0x0a, 0x07, 0x57, 0x49,
	0x4e, 0x44, 0x4f, 0x57, 0x53, 0x10, 0x04, 0x12, 0x07, 0x0a, 0x03, 0x57, 0x45, 0x42, 0x10, 0x05,
	0x2a, 0x4a, 0x0a, 0x0c, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52,
	0x12, 0x18, 0x0a, 0x14, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x41, 0x56, 0x41, 0x54,
	0x41, 0x52, 0x5f, 0x4f, 0x57, 0x4e, 0x45, 0x52, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x55, 0x53,
	0x45, 0x52, 0x5f, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x43,
	0x48, 0x41, 0x54, 0x5f, 0x41, 0x56, 0x41, 0x54, 0x41, 0x52, 0x10, 0x02, 0x2a, 0x3e, 0x0a, 0x0c,
	0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x12, 0x18, 0x0a, 0x14,
	0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x5f, 0x41, 0x43, 0x43, 0x4f, 0x55, 0x4e, 0x54, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4d, 0x4f, 0x42, 0x49, 0x4c, 0x45,
	0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x4c, 0x41, 0x52, 0x4b, 0x10, 0x02, 0x42, 0x15, 0x5a, 0x13,
	0x2e, 0x2f, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x3b, 0x70, 0x62, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pbentity_user_proto_rawDescOnce sync.Once
	file_pbentity_user_proto_rawDescData = file_pbentity_user_proto_rawDesc
)

func file_pbentity_user_proto_rawDescGZIP() []byte {
	file_pbentity_user_proto_rawDescOnce.Do(func() {
		file_pbentity_user_proto_rawDescData = protoimpl.X.CompressGZIP(file_pbentity_user_proto_rawDescData)
	})
	return file_pbentity_user_proto_rawDescData
}

var file_pbentity_user_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pbentity_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pbentity_user_proto_goTypes = []interface{}{
	(PLATFORM_TYPE)(0), // 0: pbentity.PLATFORM_TYPE
	(AVATAR_OWNER)(0),  // 1: pbentity.AVATAR_OWNER
	(ACCOUNT_TYPE)(0),  // 2: pbentity.ACCOUNT_TYPE
	(*Info)(nil),       // 3: pbentity.Info
	(*AvatarInfo)(nil), // 4: pbentity.AvatarInfo
}
var file_pbentity_user_proto_depIdxs = []int32{
	4, // 0: pbentity.Info.avatar:type_name -> pbentity.AvatarInfo
	1, // 1: pbentity.AvatarInfo.owner_type:type_name -> pbentity.AVATAR_OWNER
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pbentity_user_proto_init() }
func file_pbentity_user_proto_init() {
	if File_pbentity_user_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pbentity_user_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pbentity_user_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AvatarInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pbentity_user_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_user_proto_goTypes,
		DependencyIndexes: file_pbentity_user_proto_depIdxs,
		EnumInfos:         file_pbentity_user_proto_enumTypes,
		MessageInfos:      file_pbentity_user_proto_msgTypes,
	}.Build()
	File_pbentity_user_proto = out.File
	file_pbentity_user_proto_rawDesc = nil
	file_pbentity_user_proto_goTypes = nil
	file_pbentity_user_proto_depIdxs = nil
}
