// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"AuthServer/internal/dao/internal"
)

// internalAvatarsDao is internal type for wrapping internal DAO implements.
type internalAvatarsDao = *internal.AvatarsDao

// avatarsDao is the data access object for table avatars.
// You can define custom methods on it to extend its functionality as you wish.
type avatarsDao struct {
	internalAvatarsDao
}

var (
	// Avatars is globally public accessible object for table avatars operations.
	Avatars = avatarsDao{
		internal.NewAvatarsDao(),
	}
)

// Fill with you ideas below.
