nacos:
  ClientConfig:
    NamespaceId: "9c1232d-b9a1231e-f7f64432141235f50e5"
    CacheDir:    "/tmp/nacos"
    LogDir:      "/tmp/nacos"
    Username:    "nacos"
    Password:    "nacos"
  ConfigParam:
    DataId: "auth_config"
    Group:  "auth_config"
  ServerConfig: 
    - IpAddr: "124.123.89.188"
      Port:   8848

  






